apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - key-validator.yaml

components:
  - ../../components/validation-server

patches:
  - path: patch-http-auth.yaml
