#!/usr/bin/env bash
# Generate the demo SSH keypair and pubkeys ConfigMap.
# All three files are gitignored (treated as derived state) and recreated here.
# Idempotent: skips key generation if the private key already exists, but always
# rebuilds the ConfigMap from the current .pub files (so user-added keys are
# picked up automatically).
set -euo pipefail

KEY_DIR="k8s/overlays/file-auth/ssh-keys"
KEY_FILE="${KEY_DIR}/demo"
CONFIGMAP="k8s/overlays/file-auth/pubkeys-configmap.yaml"

if [ ! -f "$KEY_FILE" ]; then
  ssh-keygen -t ed25519 -f "$KEY_FILE" -C "demo@asd-tunnel-k8s" -N "" -q
  echo "Generated demo keypair"
else
  echo "Demo keypair already exists, skipping key generation"
fi

# Always rebuild the ConfigMap so it stays in sync with the .pub files.
echo "# ConfigMap holding authorized SSH public keys." > "$CONFIGMAP"
echo "# Auto-generated by scripts/generate-demo-key.sh — do not edit manually." >> "$CONFIGMAP"
echo "apiVersion: v1" >> "$CONFIGMAP"
echo "kind: ConfigMap" >> "$CONFIGMAP"
echo "metadata:" >> "$CONFIGMAP"
echo "  name: tunnel-pubkeys" >> "$CONFIGMAP"
echo "  namespace: asd-tunnel-demo" >> "$CONFIGMAP"
echo "data:" >> "$CONFIGMAP"

for pubfile in "${KEY_DIR}"/*.pub; do
  name=$(basename "$pubfile")
  key=$(cat "$pubfile")
  echo "  ${name}: |" >> "$CONFIGMAP"
  echo "    ${key}" >> "$CONFIGMAP"
done

echo "Updated pubkeys-configmap.yaml with $(ls "${KEY_DIR}"/*.pub | wc -l) key(s)"
