#!/usr/bin/env bash
# Generate the demo SSH keypair and update the pubkeys ConfigMap.
# Idempotent: skips if the private key already exists.
set -euo pipefail

KEY_DIR="k8s/overlays/file-auth/ssh-keys"
KEY_FILE="${KEY_DIR}/demo"
CONFIGMAP="k8s/overlays/file-auth/pubkeys-configmap.yaml"

if [ -f "$KEY_FILE" ]; then
  echo "Demo keypair already exists, skipping"
  exit 0
fi

ssh-keygen -t ed25519 -f "$KEY_FILE" -C "demo@asd-tunnel-k8s" -N "" -q
echo "Generated demo keypair"

pubkey=$(cat "${KEY_FILE}.pub")

cat > "$CONFIGMAP" << EOF
# ConfigMap holding authorized SSH public keys.
# Auto-generated by scripts/generate-demo-key.sh — do not edit manually.
apiVersion: v1
kind: ConfigMap
metadata:
  name: tunnel-pubkeys
  namespace: asd-tunnel-demo
data:
  demo.pub: |
    ${pubkey}
EOF

echo "Updated pubkeys-configmap.yaml"
